### ISSUE TITLE
mycroft.audio.audioservice:load_services error

### ISSUE THREAD

**Issue by emphasize** [JarbasAl/py_mplayer#3]
```
2020-09-06 20:39:38.227 | ERROR    |   774 | mycroft.audio.audioservice:load_services:114 | Failed to import module mplayer
SyntaxError('invalid syntax', ('/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/py_mplayer/__init__.py', 799, 29, '            except Exception, e:\n'))
```

Bit of context. I was installing the package since one of your skills (hivemind/node red; that's the only ones from your library) appearently require this to work properly. Stumbled accross this troubleshooting some audio problems and audio.log logging some py_mplayer import problems   

This is from the boot up process. No interaction prior to this.

Greets

**Comment by goldyfruit** [comment]
Same for me with the current `dev` version.

**Comment by emphasize** [comment]
This is just an artifact not properly managed by MycroftAI. This notification existed even before installing Jarbas' skills, i just glossed over and it came up during troubleshooting another issue
